### ISSUE TITLE
How large is too large?

### ISSUE THREAD

**Issue by efreethy** [GeoTIFF/georaster-layer-for-leaflet#117]
The docs state "Loads large geotiffs greater than a hundred megabytes".

I have some heavy COG geotiffs weighing in at 500 megabytes. Will this tool support that?

**Comment by DanielJDufour** [comment]
hey, great question!  It should work okay as long as the COG has a low-res overviews for when you are zoomed out.

**Comment by DanielJDufour** [comment]
let me know if you run into any problems.  there's some other issues that can appear when dealing with really large geotiffs.  for example if you are using a floating point bit depth, decompressing a tile can lead to memory and max array length issues, so you may need to look at bit depth and tile size, too.

**Comment by efreethy** [comment]
You are incredibly helpful thank you!

>  as long as the COG has a low-res overviews for when you are zoomed out.

Is there a recommended approach here? Currently using `gdalwarp` with mostly defaults

> for example if you are using a floating point bit depth, decompressing a tile can lead to memory and max array length issues

I will keep that in mind - working with 1 band of Float32, however it only needs to represent values between 0 and 5.

**Comment by efreethy** [comment]
Using your library I was able to achieve this within minutes:

<img width="1157" alt="Screen Shot 2023-02-01 at 2 23 21 PM" src="https://user-images.githubusercontent.com/12145559/216179032-a64421ca-ed80-442b-9a0f-819942ffc250.png">

You are a hero

**Comment by DanielJDufour** [comment]
glad to hear it!  thanks for the kind words :-)

to answer your previous question, I think if you use gdalwarp with `-of COG`, you should be fine (see https://gdal.org/drivers/raster/cog.html)
<img width="944" alt="Screen Shot 2023-02-01 at 6 36 35 PM" src="https://user-images.githubusercontent.com/4313463/216192109-4bee9caa-5546-47bb-a40f-31a72555dac0.png">
