### ISSUE TITLE
How can you extract bands from a geotiff?

### ISSUE THREAD

**Issue by john-a-m** [GeoTIFF/georaster-layer-for-leaflet#144]
I noticed when browsing through the issues that issue #67 seems to imply that it is possible to visualize a band by providing a `pixelValuesToColorFn` which sounds good to me. Is there an example of how to leverage `pixelValuesToColorFn` to do this?

**Comment by DanielJDufour** [comment]
Sure thing. Here's a few examples:
- https://github.com/GeoTIFF/georaster-layer-for-leaflet-example/blob/master/examples/ndvi.html
- https://github.com/GeoTIFF/georaster-layer-for-leaflet-example/blob/master/examples/population.html
- https://github.com/GeoTIFF/georaster-layer-for-leaflet-example/blob/master/examples/identifying-wildfires-with-landsat.html

Let me know if you have any more questions!

**Comment by john-a-m** [comment]
If anyone comes across this what is important to know is that if a geotiff has bands then `pixelValuesToColorFn` will be given an array of `values` rather than a singular `value`. The population example highlights this well.


    var layer = new GeoRasterLayer({
        attribution: "European Commission: Global Human Settlement",
        georaster: georaster,
        opacity: 0.75,
        resolution: 64,
        pixelValuesToColorFn: function (values) {
          var population = values[0];
          if (population === -200) return;
          if (population < 0) return;
          return scale(population).hex();
        }
    });
