### ISSUE TITLE
Allow transparency without a Mask via pixelValuesToColorFn

### ISSUE THREAD

**Issue by jfoclpf** [GeoTIFF/georaster-layer-for-leaflet#145]
First of all PROPS for you guys for developing this GREAT AND FREE tool, thanks a lot

**Is your feature request related to a problem?**
I have this elevation map with lots of zeros mapped to white, it would be nice to have transparency for values under zero, for example

![image](https://github.com/GeoTIFF/georaster-layer-for-leaflet/assets/3984909/2ee3b700-7cd0-40cd-b43a-2ed67df25daf)

**Describe the solution you'd like**

Allowing transparency without the need for an external GeoJSON mask via `pixelValuesToColorFn`

```js
      var layer = new GeoRasterLayer({
          georaster: georaster,
          opacity: 0.7,
          pixelValuesToColorFn: values => values[0] < 0 ? 'transparent' : '#ffffff',
          resolution: 64 // optional parameter for adjusting display resolution
      });
```

**Describe alternatives you've considered**

Use an external GeoJSON file for the mask

**Additional context**
Working example I just made using your tool: https://stackoverflow.com/a/78298578/1243247

Again, thanks a lot for the great tool

**Comment by jfoclpf** [comment]
Found it :) `null` was the trick, perhaps docs should be more clear

```js
      const layer = new GeoRasterLayer({
        georaster: georaster,
        opacity: 0.7,
        pixelValuesToColorFn: vals => Math.round(vals[0]) < 1 ? null : '#ffffff',
        resolution: 512 // optional parameter for adjusting display resolution
      }).addTo(map)
```

again, congrats for the great work @DanielJDufour

**Comment by DanielJDufour** [comment]
@jfoclpf , would you be open to submitting a PR, adding this example to https://github.com/GeoTIFF/georaster-layer-for-leaflet-example

?

**Comment by jfoclpf** [comment]
> @jfoclpf , would you be open to submitting a PR, adding this example to https://github.com/GeoTIFF/georaster-layer-for-leaflet-example
> 
> ?

sure, I will do it ASAP
