### ISSUE TITLE
Display data as direction arrows

### ISSUE THREAD

**Issue by khannurien** [GeoTIFF/georaster-layer-for-leaflet#17]
Hi!

It would be great if we could display raster data as direction arrows such as in the leaflet-geotiff plugin:
https://github.com/stuartmatthews/leaflet-geotiff

I don't have any idea of the workload involved; sorry if this request seems unrealistic.

**Comment by DanielJDufour** [comment]
Done.  Here's the documentation: https://github.com/GeoTIFF/georaster-layer-for-leaflet/blob/master/ADVANCED.md

However, I've taken a different approach from Stuart Matthews although I love leaflet-geotiff and it's such an awesome project.  Honestly, I don't have enough time to maintain a specific arrow drawing functionality.  I'm hoping by allowing users to pass in their own custom drawing function, I can give a little more power and responsibility to the users/developers and reduce my long-term maintenance cost.  I'm committed to this library and geotiff.io, but there's only so much time in the day.

The example is a little weird though.  If you'd like to fix it or improve on it, I'm definitely open to pull requests!

Thank you for your feedback and looking forward to your contributions!
