### ISSUE TITLE
parse_georaster is not defined

### ISSUE THREAD

**Issue by luisete2** [GeoTIFF/georaster-layer-for-leaflet#23]
I think this may be a very basic issue but I'm struggling to get this working. I'm working with plain JS.

I add the package via script tag: 
`<script src="https://unpkg.com/georaster-layer-for-leaflet/georaster-layer-for-leaflet.browserify.min.js"></script>`

Georaster is also included. I copied the example code and got this error with the first two "require" lines:
`ReferenceError: require is not defined`

So... I checked require.js and downloaded it, but got another error derived of loading the script two times, once in HTML and once in JS. I got rid of the requires and now I have parse_georaster not defined because... it isn't defined, obviously, but how can I get this working? I'm a bit lost...

Thanks in advance.

**Comment by DanielJDufour** [comment]
Hi, if you load georaster and georaster-layer-for-leaflet via a script tag, you can call `parseGeoRaster` instead of parse_georaster.  Here's an example: https://github.com/GeoTIFF/georaster-layer-for-leaflet-example/blob/master/examples/load-via-script-tag.html  As you can see in the example, there are no `require` statements required :-)

Let me know if that helps!  If not, I'm happy to improve documentation for you and others =)

**Comment by luisete2** [comment]
Okay that solved it! Perfect.

Now my problem I believe is that the TIFs I'm working with are way too big, about 130 MB, and they're not being displayed. Any clue on this?

**Comment by DanielJDufour** [comment]
No problem! You'll want to consult this example.  https://github.com/GeoTIFF/georaster-layer-for-leaflet-example/blob/master/examples/load-cog-via-script-tag.html

It renders a 800MB cloud optimized geotiff. The demo is here https://geotiff.github.io/georaster-layer-for-leaflet-example/examples/load-cog-via-script-tag.html

Let me know if you have any additional questions :-)

**Comment by DanielJDufour** [comment]
Hi, @luisete2 .  You may want to consider using geoblaze to identify pixels in a georaster.  Here's an example:

https://observablehq.com/@danieljdufour/identify-single-pixel-value-in-geotiff

You can also use GeoBlaze to get the sum of an area:
https://observablehq.com/@danieljdufour/hectares-of-rainfed-wheat-in-ukraine

Happy to take a look at your code once you have it uploaded! :-)

**Comment by luisete2** [comment]
Okay, beginning now to use Geoblaze. How can I call the Geoblaze object if I'm importing it from a script in html? Because I see that in the first script you're declaring the geoblaze item as a require. It's the same if I use a script tag?

Btw, my code is now online at http://optren.es/test/
Right now using georaster-layer-for-leaflet and geoblaze.

**Comment by DanielJDufour** [comment]
Hi, @luisete2  .  I created an example for you.  Could you check it out and let me know if it helps?  As you can see in the example, you don't need to run geoblaze.load:

https://github.com/GeoTIFF/georaster-layer-for-leaflet-example/blob/master/examples/load-via-script-tag-with-geoblaze.html

https://geotiff.github.io/georaster-layer-for-leaflet-example/examples/load-via-script-tag-with-geoblaze.html

**Comment by DanielJDufour** [comment]
Also, you're working on an awesome project!

**Comment by DanielJDufour** [comment]
hello.  I'm closing this issue as the issue has gone stale.  Please reopen or open a new issue if you are having problems.  Thank you.
