### ISSUE TITLE
Colored tif rendered in bn

### ISSUE THREAD

**Issue by Deca** [GeoTIFF/georaster-layer-for-leaflet#24]
Not sure if is a bug, this is my first time I work with geotiff
I'm trying your example with a colored tif I should work with but It appear on the map in black and white...is there something I'm missing?
![image](https://user-images.githubusercontent.com/3716783/69230714-17254e00-0b88-11ea-838c-f8b91ebd5fce.png)

**Comment by DanielJDufour** [comment]
Hi, @Deca .  Welcome to GeoTIFFs!  Would you happen to be able to share the GeoTIFF file you are trying to render?  That will be the easiest way for me to debug this for you.

If not could you take a screenshot of the dev console (what is logged when you run `console.log("georaster:", georaster);` and/or run `gdalinfo example.tif` with example.tif replaced by your filename.

Thanks!

**Comment by DanielJDufour** [comment]
If you'd like to send me the geotiff, you can send it to daniel.j.dufour@gmail.com

**Comment by Deca** [comment]
Hi Daniel and thanks for the reply, I add as archive the tif I'm using and the georaster obj I got from console
[tif_log.zip](https://github.com/GeoTIFF/georaster-layer-for-leaflet/files/3870066/tif_log.zip)

**Comment by vmandal** [comment]
What was the solution? Or do we need to use "pixelValuesToColorFn" and manually set color? Can it not automatically display the colors?

**Comment by Deca** [comment]
Unresolved from my side, I settled for using simple png but I still would like switch to geotiff
Let's see if Daniel have some news

**Comment by DanielJDufour** [comment]
This should be fixed now.  Please upgrade georaster and georaster-layer-for-leaflet to the newest version.  You can see it in action here: https://geotiff.github.io/georaster-layer-for-leaflet-example/examples/load-file.html if you load a file with a ColorTable.  Let me know if it works! Thank you for your patience.

<img width="1437" alt="Screen Shot 2020-06-27 at 6 04 12 PM" src="https://user-images.githubusercontent.com/4313463/85933063-9c9c7980-b8a0-11ea-80f7-ae296c1f87a9.png">

**Comment by vmandal** [comment]
Excellent work!  
Thank you very much @DanielJDufour

**Comment by DanielJDufour** [comment]
Glad to hear it! I'll close this issue for now. Please post any future issues again. Thank you both!
