### ISSUE TITLE
Proposal: custom value to color function

### ISSUE THREAD

**Issue by GabiAxel** [GeoTIFF/georaster-layer-for-leaflet#3]
Greetings. I had a usecase in which I needed to show specific colors for specific pixel values in a GeoTIFF. I resolved it by modifying https://github.com/GeoTIFF/georaster-layer-for-leaflet/blob/master/georaster-layer-for-leaflet.js#L149 so that it would accept a function option that does this translation, something like this:
```javascript
if(this.options.colorFn) {
  color = this.options.colorFn(values[0])
} else {
  // previous behavior
}
```

In my case it was always a single value and nothing else (such as min or range) mattered, but maybe for a generic case the function should be able to receive more parameters.

**Comment by DanielJDufour** [comment]
Awesome. I love this idea!  Would you like to submit a pull request?  I can also take your code and make the PR myself.  Whatever works for you :-)

**Comment by GabiAxel** [comment]
Thanks. Submitted #4

**Comment by DanielJDufour** [comment]
FYI: I republished with your commit: https://www.npmjs.com/package/georaster-layer-for-leaflet

Closing this issue now.  Thanks again!
