### ISSUE TITLE
Add GeoJSON Mask Option

### ISSUE THREAD

**Issue by DanielJDufour** [GeoTIFF/georaster-layer-for-leaflet#34]
```js
new GeoRasterLayer({
    georaster,
    bounds: geojson
})
```

This would mean only display within the bounds.

**Comment by DanielJDufour** [comment]
Might be more intuitive to say:
```js
new GeoRasterLayer({
    georaster,
    mask: geojson
})
```

**Comment by DanielJDufour** [comment]
@m-mohr

**Comment by m-mohr** [comment]
How much effort would this be?

**Comment by prakashmani2495** [comment]
Hi,
You did a excellent work which saved me a lot to work on georaster files.
 Can you please help, how to remove the excess layer (outside the polygon), I want the clip/mask the georaster layer with polygon on leaflet and here I'm using 4326 projection. Here I'm attaching the screen shot for reference
 
![screen shot](https://user-images.githubusercontent.com/53475193/154854276-51a4ac9d-bf0b-4305-aa79-5c12dbad07b8.png)
.

**Comment by DanielJDufour** [comment]
Hi, @prakashmani2495.  Thanks for helping validate this important use case.  You can't clip/mask with GeoRasterLayer yet, but it's a high priority to me to get this done.  I've been working on some of the dependencies for this task, which you can view here: https://observablehq.com/@danieljdufour/clip-and-reproject-a-geotiff-with-geowarp.  

Unfortunately, it'll probably take a few days of concerted effort to get this done.  I should have time in a couple months when my schedule lightens a little.

In the interim, you could try cropping your GeoTIFF before visualization using [gdalwarp](https://gdal.org/programs/gdalwarp.html)'s cutline functionality.

Let me know if you have any more questions.  Happy to answer and sorry for the delay.  I too want this feature very much! :-)

**Comment by prakashmani2495** [comment]
Hi Daniel,

Thank you for the quick response. Will try using [gdalwarp](https://gdal.org/programs/gdalwarp.html)'s cutline functionality. Please make this a priority item, since I wanted this feature urgently.

**Comment by DanielJDufour** [comment]
This was completed.  You can find the documentation here: https://github.com/GeoTIFF/georaster-layer-for-leaflet/blob/master/ADVANCED.md#masking
