### ISSUE TITLE
ReferenceError: Can't find variable: proj4

### ISSUE THREAD

**Issue by YANI-ALT** [GeoTIFF/georaster-layer-for-leaflet#41]
Hello! 
I am a beginner using this for my project. I got the following error in console not sure what it means...please tell me how I should go about debugging.
I'm using macOS Mojave and safari.

![image](https://user-images.githubusercontent.com/56057217/88507269-ab8a5f00-cff9-11ea-845f-f072d1bd0e8f.png)

The error directs to this portion of the code in : georaster-layer-for-leaflet.browserify.min.js

![image](https://user-images.githubusercontent.com/56057217/88507401-f73d0880-cff9-11ea-9cc9-6791ac8ab736.png)

**Comment by DanielJDufour** [comment]
Hello.  Thank you for posting this issue.  It's a very common issue and I should update the error to be more clear.  I added another entry to the FAQ to answer this: https://github.com/GeoTIFF/georaster-layer-for-leaflet/blob/master/FAQs.md#i-receive-a-referenceerror-cant-find-variable-proj4

Let me know if this helps!

**Comment by DanielJDufour** [comment]
Hi, @YANI-ALT .  Did the answer help? Thanks!

**Comment by YANI-ALT** [comment]
yes this should do ! Thanks

**Comment by DanielJDufour** [comment]
Awesome!
