### ISSUE TITLE
Remove GeoRasterLayer

### ISSUE THREAD

**Issue by aaronyeo40** [GeoTIFF/georaster-layer-for-leaflet#49]
Hi,
    May I know how to remove the layer?

thanks 

regard

Aaron

**Comment by aaronyeo40** [comment]
var layer = new GeoRasterLayer({
                            georaster: georaster,
                            resolution: 256
                        });
                        layer.addTo(map);
                        map.fitBounds(layer.getBounds());

after tested just remove the **var** 

 map.removeLayer(layer);

is it this is the correct way or any alternative?

thanks

**Comment by DanielJDufour** [comment]
Yup. That's correct.  Thanks for posting this!  It helps others who have the same question :-)

**Comment by DanielJDufour** [comment]
@aaronyeo40 solved the issue, so I'm going to close this issue.  Please open new issues as problems come up as it helps everyone.  Thank you very much!
