### ISSUE TITLE
Doubled pixels at high zoom levels

### ISSUE THREAD

**Issue by jcphill** [GeoTIFF/georaster-layer-for-leaflet#62]
**Describe the bug**
When zoomed in past native raster resolution some rows and columns of pixels are doubled.

**To Reproduce**
1. Download and unzip [check.tif.gz](https://github.com/GeoTIFF/georaster-layer-for-leaflet/files/6229759/check.tif.gz)
2. Load into https://geotiff.github.io/georaster-layer-for-leaflet-example/examples/load-file.html
3. Zoom in.

**Expected behavior**
A regular checkerboard pattern should be displayed.

**Screenshots**
<img width="661" alt="Pixel_aliasing" src="https://user-images.githubusercontent.com/16992184/113006068-a35f6200-913a-11eb-8975-5462a1c2aae5.png">

**Desktop (please complete the following information):**
 - Mac OS
 - Firefox or Chrome
 - Latest versions

**Comment by DanielJDufour** [comment]
Hi, @jcphill .  Thank you for catching this!  I'll definitely take a look.

**Comment by jcphill** [comment]
#78 should fix this.

**Comment by DanielJDufour** [comment]
@jcphill , I added a specific test case for this, merged your PR, and republished.  Thank you so much!
