### ISSUE TITLE
Unstable drawing 3.0.1

### ISSUE THREAD

**Issue by ayerix** [GeoTIFF/georaster-layer-for-leaflet#74]
Geotiff attached below works stable on 2.0.2 and has significant gaps (different on different scales) on 3.0.1
See geotiff and drawing examples in attach
[__Chel4_v2.zip](https://github.com/GeoTIFF/georaster-layer-for-leaflet/files/7090775/__Chel4_v2.zip)
[screens.zip](https://github.com/GeoTIFF/georaster-layer-for-leaflet/files/7090784/screens.zip)
leaflet 1.7.1, georaster parser 1.5.4

**Comment by DanielJDufour** [comment]
Hi, @ayerix .  Thanks for sharing this.  I'm sorry for the inconvenience this has caused.  Does it load correctly when you load the GeoTIFF at https://geotiff.github.io/georaster-layer-for-leaflet-example/examples/load-file.html?

**Comment by ayerix** [comment]
Works ok here, no missing straps, not reproduced. But I don't see plugin versions, so I can't say for sure about it's difference

**Comment by DanielJDufour** [comment]
I updated the example to use Leaflet 1.7.1 and it appears to continue to work.  Here's the new versions:
- georaster: 1.5.4
- georaster-layer-for-leaflet: 3.1.2
- leaflet: 1.7.1

Could you try with georaster-layer-for-leaflet 3.1.2 and see if any of the recent changes fixed the bug for you?

Could it be a CSS issue?  I'm sorry I haven't been more helpful.

**Comment by benhid** [comment]
@DanielJDufour CSS issue indeed!

I'm using tailwindcss and it comes with a [set of base styles](https://tailwindcss.com/docs/preflight) -Preflight- built on top of  [_modern-normalize_](https://github.com/sindresorhus/modern-normalize).

It seems like _modern-normalize_ sets `box-sizing: border-box`. Hence using

```js
.leaflet-container * {
    box-sizing: initial;
}
```

solved the issue for me 👏🏻

**Comment by DanielJDufour** [comment]
hey, @ayerix .  Thank you for figuring this out!  I made a [fix](https://github.com/GeoTIFF/georaster-layer-for-leaflet/commit/62433a50f23e5350526c7ad3eef799640a927f25) and republished the library, so you shouldn't need to use `.leaflet-container * { box-sizing: initial; }` anymore.  You really helped people me make sure GeoRasterLayer works with tailwindcss and other css libraries.  Thank you!

Please open any more issues you find.
