### ISSUE TITLE
Scattered tiles in version 3.x

### ISSUE THREAD

**Issue by vlach1989** [GeoTIFF/georaster-layer-for-leaflet#75]
I'm trying to reproduce following example: https://geotiff.github.io/georaster-layer-for-leaflet-example/examples/load-cog-via-script-tag.html wrapped with React-Leaflet

It works as expected in version 2.0.2. However, both in version 3.0.2 and 3.1.1 (the latest) the tiles are somehow scattered or missing:

![image](https://user-images.githubusercontent.com/16032132/131685380-29602790-fe22-4e1a-ab38-9c862b652f06.png)

I found out, that at least the calculated position for some tiles is wrong or padding is too big.

**Comment by DanielJDufour** [comment]
Hi, @vlach1989 .  Thanks for sharing this.  Would you be able to share the code you are using?  Also, what browser are you using?  Thank you!

**Comment by geojs** [comment]
@vlach1989 I had the same issue (Leaflet 1.7.1 + Chromium 93), the last version of georaster-layer-for-leaflet [v3.2.0](https://github.com/GeoTIFF/georaster-layer-for-leaflet/releases/tag/v3.2.0) fix the issue.

**Comment by vlach1989** [comment]
I confirm, that v3.2.0 fixes the issue

**Comment by DanielJDufour** [comment]
Glad to hear it!
