### ISSUE TITLE
Resampling bug?

### ISSUE THREAD

**Issue by vlach1989** [GeoTIFF/georaster-layer-for-leaflet#86]
Hi,

I came accross the following bug. I have a COG where the pixel values are: 0 - no data, 1 - irrigation, 2 - no irrigation. PixelValuesToColorFn is used for styling, where for value 0 no color is applied, the raster is transparent in those places, value 1 is represented by blue color and value 2 is represented by grey color. As you can see in the attached image, strange "edges" are created between the regions. 

![resampling_github](https://user-images.githubusercontent.com/16032132/142625525-7340f76b-e14f-4c59-bc92-121c280d8cf3.PNG)

**Expected behavior**
In this image where the same data is visualized in QGIS you can see the correct behavior.
![qgis](https://user-images.githubusercontent.com/16032132/142625631-44b5020f-3924-47a8-91f5-ee856cd658c1.PNG)

**Comment by DanielJDufour** [comment]
Hi.  I think this might be an issue with bilinear resampling.  You can try nearest resampling like so:

```js
new GeoRasterLayer({ georaster, resampleMethod: "nearest" })
```

Let me know if that fixes it for you!

**Comment by vlach1989** [comment]
Hi. It works! Thanks so much for tip as well as quick response!

![image](https://user-images.githubusercontent.com/16032132/142630864-f0f3d400-cd1a-4c6a-8cdf-064d07d838c3.png)
