### ISSUE TITLE
Support YCbCr

### ISSUE THREAD

**Issue by DanielJDufour** [GeoTIFF/georaster-layer-for-leaflet#88]
Related:
https://github.com/radiantearth/stac-browser/issues/108#issuecomment-994661736

**Comment by DanielJDufour** [comment]
I "think" YCbCr could be currently achieved by passing in a pixelValuesToColorFn that converts [Y, Cb, Cr] to `"rgba(r, g, b, a)"`.

But it would be better to have georaster-layer-for-leaflet natively support this by creating this pixelValuesToColorFn if Photometric tag is YCBCR and no pixelValuesToColorFn is supplied.

**Comment by DanielJDufour** [comment]
@drwelby , could you provide a direct link to a YCbCr geotiff?  I'll try to add an example visualizing YCbCr to https://github.com/geotiff/georaster-layer-for-leaflet-example once I got that.  Thank you for brining this issue to our attention.  I've just been reading up on YCbCr since then and it's fascinating stuff!

**Comment by drwelby** [comment]
You and @mmohr are too fast, I started writing out a feature request for this last night!

 We've done it by supplying a `pixelsValueToColorFn`: 

```javascript
function ycbcr2color (values){
    const r = Math.round(values[0] + 1.40200 * (values[2] - 0x80));
    const g = Math.round(values[0] - 0.34414 * (values[1] - 0x80) - 0.71414 * (values[2] - 0x80));
    const b = Math.round(values[0] + 1.77200 * (values[1] - 0x80));
    return `rgb(${r},${g},${b})`;
} 
```

but had not gone to the point of making the detection automatic, or any other features like adding an option to force a color mode.

Here's a YCbCr COG for testing:

https://maxar-ard-samples.s3.amazonaws.com/v3/australia_vineyards/50/213133231011/2019-10-07/10500100191CD200-visual.tif

**Comment by DanielJDufour** [comment]
@drwelby , thank you.  That is very helpful!  I've added an example here: https://geotiff.github.io/georaster-layer-for-leaflet-example/examples/ycbcr.html

**Comment by DanielJDufour** [comment]
Updating georaster-layer-for-leaflet might be a bit tricky as I don't think the georaster dependency reveals this information.  I'll try to see if there's an easy way to access the Photometric Interpretation metadata.  Just curious, is photometric interpretation something that is stored in the STAC metadata?
@m-mohr

**Comment by drwelby** [comment]
We could certainly go in the direction of using STAC metadata for color interpretation if needed.

**Comment by drwelby** [comment]
I can see `PhotometricInterpretation: 6` in the `IFDRequests` but it seems kind of clunky not to expose the other geotiff tags, as how the geotransform is extracted.

**Comment by DanielJDufour** [comment]
I think I'll be able to add this with the following code:
```js
if ((await georaster?._geotiff.getImage()).fileDirectory.PhotometricInterpretation === 6) {
    pixelValuesToColorFn ??= function ycbcr2color (values){
      const r = Math.round(values[0] + 1.40200 * (values[2] - 0x80));
      const g = Math.round(values[0] - 0.34414 * (values[1] - 0x80) - 0.71414 * (values[2] - 0x80));
      const b = Math.round(values[0] + 1.77200 * (values[1] - 0x80));
      return `rgb(${r},${g},${b})`;
    } 
}
```

**Comment by DanielJDufour** [comment]
give me a day or two.  the release process is rather lengthy with a lot of checks.  this change should then percolate up to stac-layer and stac-browser.

**Comment by DanielJDufour** [comment]
not yet, sir.  I'll try to get to it this weekend. sorry.

**Comment by DanielJDufour** [comment]
A new version of GeoRasterLayer for Leaflet has been published that includes the YCbCr support.  Thank you!

**Comment by drwelby** [comment]
Thanks to you too!
