### ISSUE TITLE
Overviews not showing properly for categorical map

### ISSUE THREAD

**Issue by glaroc** [GeoTIFF/georaster-layer-for-leaflet#96]
I've generated a COG of a land cover (integer) map and hosted it on the cloud. I used gdalwarp with nearest resampling for the creation of the cog and the overviews. I used pixelValuesToColorFn to assign a distinct color for every land cover category. When loaded in georaster-layer-for-leaflet, there are "holes" of transparency in the map. It appears that the overviews contain interpolated values that don't correspond to one of the values of the raster. If I debug the pixelValuesToColorFn function, I see some values are passed to it that are not on the actual map. When I zoom in to have the tiles at the maximum resolution, all colors are ok. 

See this screenshot
![Screenshot from 2022-05-12 16-31-28](https://user-images.githubusercontent.com/2243493/168162895-e9139079-4f17-46ad-9294-dc5bad7c7869.png)

When I load the same map from the URL in QGIS, I don't get this problem, at any zoom level. 
![Screenshot from 2022-05-12 16-29-11](https://user-images.githubusercontent.com/2243493/168162645-90ee3826-58ce-407f-88e1-9da5983af21c.png)

With v 3.7.2

**Comment by DanielJDufour** [comment]
Hi.  Does this link help? https://github.com/GeoTIFF/georaster-layer-for-leaflet/issues/86#issuecomment-974067073

**Comment by glaroc** [comment]
Absolutely! It works like a charm now. 

I couldn't find a resampling option in the documentation. Is this documented somewhere ? 

Thank you!
